

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proyecto_bar
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data

